"""empty message

Revision ID: 03a65451f783
Revises: 552c63be3b27
Create Date: 2017-10-20 02:39:12.140571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a65451f783'
down_revision = '552c63be3b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'is_open')
    # ### end Alembic commands ###
