"""empty message

Revision ID: 03d78b36ba3a
Revises: a6640538a149
Create Date: 2017-10-30 23:58:02.577629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d78b36ba3a'
down_revision = 'a6640538a149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_first_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_first_time')
    # ### end Alembic commands ###
