"""empty message

Revision ID: 53315a68d89a
Revises: 6fea18e2cf67
Create Date: 2017-10-19 17:17:21.838838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53315a68d89a'
down_revision = '6fea18e2cf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'start_time')
    op.drop_column('group', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('end_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('group', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
