"""empty message

Revision ID: 552c63be3b27
Revises: 53315a68d89a
Create Date: 2017-10-19 17:17:51.049241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552c63be3b27'
down_revision = '53315a68d89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('group', sa.Column('start_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'start_time')
    op.drop_column('group', 'end_time')
    # ### end Alembic commands ###
