"""empty message

Revision ID: 6fea18e2cf67
Revises: dbbbf7893e62
Create Date: 2017-10-19 17:08:40.845734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fea18e2cf67'
down_revision = 'dbbbf7893e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_session_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_session_generated')
    # ### end Alembic commands ###
