"""empty message

Revision ID: 97bc91c1ea77
Revises: 9cde3f4fee64
Create Date: 2017-10-15 01:42:47.997347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bc91c1ea77'
down_revision = '9cde3f4fee64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academictime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_name', sa.String(), nullable=True),
    sa.Column('even_odd_week', sa.String(), nullable=True),
    sa.Column('acad_year', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academictime')
    # ### end Alembic commands ###
