"""empty message

Revision ID: c966cc8ca577
Revises: ef3f338ddeb8
Create Date: 2017-10-16 03:42:20.973433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c966cc8ca577'
down_revision = 'ef3f338ddeb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
