"""empty message

Revision ID: dbbbf7893e62
Revises: c966cc8ca577
Create Date: 2017-10-19 00:50:38.296723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbbf7893e62'
down_revision = 'c966cc8ca577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courseStaff', sa.Column('role', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_data_pulled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('matric', sa.String(), nullable=True))
    op.drop_constraint('user_metric_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['matric'])
    op.drop_column('user', 'metric')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('metric', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_metric_key', 'user', ['metric'])
    op.drop_column('user', 'matric')
    op.drop_column('user', 'is_data_pulled')
    op.drop_column('courseStaff', 'role')
    # ### end Alembic commands ###
