"""empty message

Revision ID: ef3f338ddeb8
Revises: 5e0794dff225
Create Date: 2017-10-15 17:33:32.837062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3f338ddeb8'
down_revision = '5e0794dff225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('is_mocked', sa.Boolean(), nullable=True))
    op.add_column('group', sa.Column('is_mocked', sa.Boolean(), nullable=True))
    op.add_column('session', sa.Column('is_mocked', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_mocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_mocked')
    op.drop_column('session', 'is_mocked')
    op.drop_column('group', 'is_mocked')
    op.drop_column('course', 'is_mocked')
    # ### end Alembic commands ###
